name: romdoul
description: Romdoul application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.7+3
  path_provider: ^1.2.0
  http: ^0.12.0+2
  barcode_scan: ^1.0.0
  rxdart: ^0.23.1
  qr_code_tools: ^0.0.6
  image_picker: ^0.6.2+3
  toast: ^0.1.5
  flutter_colorpicker: ^0.2.6
  liquid_pull_to_refresh: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "launcher/logo.jpg"
  image_path_android: "launcher/logo.jpg"
  adaptive_icon_background: "launcher/logo.jpg"
  adaptive_icon_foreground: "launcher/logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/logo_bg.png
    - images/logo.png
    - images/icon-01.png
    - images/icon-02.png
    - images/icon-03.png
    - images/icon-04.png
    - images/icon-05.png
    - images/icon-06.png
    - images/icon-07.png
    - images/icon-08.png
    - images/icon-12.png
    - images/icon-13.png
    - images/icon-14.png
    - images/icon-15.png
    - images/icon-16.png
    - images/icon-17.png
    - images/icon-18.png
    - images/icon-19.png
    - images/icon-20.png
    - images/icon-21.png

    - images/APPLE.png
    - images/BANANA.png
    - images/BLUBERRY.png
    - images/BUBLE GYM.png
    - images/CHOCOLATE.png
    - images/CHOMPEY.png
    - images/COCONUTE.png
    - images/GRAPE.png
    - images/JASMIN.png
    - images/KIWI.png
    - images/LAVENDER.png
    - images/LYLY.png
    - images/MELON.png
    - images/ORANGE.png
    - images/ORCHID.png
    - images/PEACHE1.png
    - images/PINEAPPLE.png
    - images/ROSE1.png
    - images/SAKURA1.png
    - images/STRAWBERRY1.png
    - images/SUNFLOWER1.png
    - images/WATERMELON.png


    - images/Untitled-1-01.png
    - images/Untitled-1-02.png
    - images/Untitled-1-03.png
    - images/Untitled-1-04.png
    - images/Untitled-1-05.png
    - images/Untitled-1-06.png
    - images/Untitled-1-07.png
    - images/Untitled-1-08.png
    - images/Untitled-1-10.png
    - images/Untitled-1-11.png
    - images/Untitled-1-12.png
    - images/Untitled-1-13.png
    - images/Untitled-1-14.png
    - images/Untitled-1-15.png
    - images/Untitled-1-16.png
    - images/Untitled-1-17.png
    - images/Untitled-1-18.png
    - images/Untitled-1-19.png
    - images/Untitled-1-20.png
    - images/Untitled-1-21.png
    - images/Untitled-1-22.png
    - images/Untitled-1-23.png
    - images/Untitled-1-24.png
    - images/Untitled-1-25.png
    - images/Untitled-1-26.png
    - images/Untitled-1-27.png
    - images/Untitled-1-28.png
    - images/Untitled-1-29.png
    - images/Untitled-1-30.png
    - images/Untitled-1-31.png
    - images/Untitled-1-32.png
    - images/Untitled-1-33.png
    - images/Untitled-1-34.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
